### PR TITLE
added ProcessingJS, browserify instruction 

### PR DESCRIPTION
**Pull request by CyrusSUEN**

### CODE REVIEW

**Comment by dhowe** [comment]
You've deleted the part about:  'add the following lines, save and drag it into a browser:'

**Comment by CyrusSUEN** [comment]
Yes. Do you think that is necessary?

**Comment by dhowe** [comment]
Yes... we also need a better Processing example. Why don't you work on the other tests, then I will find an example and you can resubmit the PR tomorrow...

**Comment by CyrusSUEN** [comment]
OK. Just updated the text.

**Pull request merged**
